### ISSUE TITLE
App crashes on macOS arm

### ISSUE THREAD

**Issue by air3ijai** [getseabird/seabird#21]
Just did a try to load kubeconfig using [fresh macOS arm build](https://github.com/getseabird/seabird/actions/runs/7747847423) and app crashed
<details>
<summary>output</summary>

```
seabird_darwin_arm64 $ bash seabird.sh
2024/02/01 23:15:34 metrics disabled: No compatible metrics API detected
2024/02/01 23:15:36 metrics disabled: No compatible metrics API detected
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: closure error: unexpected panic caught: runtime error: invalid memory address or nil pointer dereference

Closure added at:
	github.com/diamondburned/gotk4/pkg/glib/v2.IdleAdd at github.com/diamondburned/gotk4/pkg@v0.1.0/glib/v2/glib.go:30348
	github.com/getseabird/seabird/ui.(*WelcomeWindow).createContent.func3.1 at github.com/getseabird/seabird/ui/welcome_window.go:79
	runtime.goexit at runtime/asm_arm64.s:1197
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x102685d1c]

goroutine 1 [running, locked to thread]:
github.com/diamondburned/gotk4/pkg/core/closure.(*FuncStack).Panicf(0x1400050f4a0, {0x10286939e, 0x1b}, {0x14000119458, 0x1, 0x1})
	github.com/diamondburned/gotk4/pkg@v0.1.0/core/closure/funcstack.go:104 +0x7f4
github.com/diamondburned/gotk4/pkg/core/closure.(*FuncStack).TryRepanic(0x14000119498?)
	github.com/diamondburned/gotk4/pkg@v0.1.0/core/closure/funcstack.go:122 +0xb8
panic({0x102e6bea0?, 0x104f63b60?})
	runtime/panic.go:914 +0x218
github.com/diamondburned/gotk4/pkg/core/glib.BaseObject(...)
	github.com/diamondburned/gotk4/pkg@v0.1.0/core/glib/glib.go:605
github.com/diamondburned/gotk4/pkg/core/glib.InternObject(...)
	github.com/diamondburned/gotk4/pkg@v0.1.0/core/glib/glib.go:612
github.com/diamondburned/gotk4-sourceview/pkg/gtksource/v5.NewBufferWithLanguage(0x0)
	github.com/diamondburned/gotk4-sourceview/pkg@v0.0.0-20240109205950-92962b56dd0f/gtksource/v5/gtksourcebuffer.go:236 +0x1c
github.com/getseabird/seabird/ui.(*DetailView).createSource(0x140002bc8c0)
	github.com/getseabird/seabird/ui/detail_view.go:280 +0x4c
github.com/getseabird/seabird/ui.NewDetailView(0x140001bb480, 0x1400059d600)
	github.com/getseabird/seabird/ui/detail_view.go:47 +0x1a8
github.com/getseabird/seabird/ui.NewClusterWindow(0x140003e9b80?, 0x140000fedc0)
	github.com/getseabird/seabird/ui/cluster_window.go:58 +0x324
github.com/getseabird/seabird/ui.(*WelcomeWindow).createContent.func3.1.1()
	github.com/getseabird/seabird/ui/welcome_window.go:87 +0xbc
github.com/diamondburned/gotk4/pkg/core/glib._gotk4_sourceFunc(0x100d)
	github.com/diamondburned/gotk4/pkg@v0.1.0/core/glib/glib.go:340 +0xdc
github.com/diamondburned/gotk4/pkg/gio/v2._Cfunc_g_application_run(0x115620fb0, 0x1, 0x600000846410)
	_cgo_gotypes.go:13798 +0x34
github.com/diamondburned/gotk4/pkg/gio/v2.(*Application).Run.func3(0x14000434840?, 0x31?, 0x600000846410?)
	github.com/diamondburned/gotk4/pkg@v0.1.0/gio/v2/gio.go:41611 +0x74
github.com/diamondburned/gotk4/pkg/gio/v2.(*Application).Run(0x14000458348, {0x1400003c0a0?, 0x1, 0x1})
	github.com/diamondburned/gotk4/pkg@v0.1.0/gio/v2/gio.go:41611 +0x1d4
github.com/getseabird/seabird/ui.(*Application).Run(0x102ba2ea0?)
	github.com/getseabird/seabird/ui/application.go:64 +0x3c
main.main()
	github.com/getseabird/seabird/main.go:21 +0xa0
seabird_darwin_arm64 $
```

<img width="1100" alt="Screenshot 2024-02-01 at 23 34 01" src="https://github.com/getseabird/seabird/assets/88528265/9a9cef28-156a-4ac0-8784-6bd5fe75d7a0">

</details>

And by the way, shouldn't app by default check `~/.kube` folder and load all configs? Or maybe at least an option to load multiple files at once.

**Comment by jgillich** [comment]
It panics because gtksourceview can't find the yaml language spec, it's a packaging issue. Closing in favor of #4
