### ISSUE TITLE
Seabird crashes when node is accessed

### ISSUE THREAD

**Issue by air3ijai** [getseabird/seabird#60]
### Issue description

Seabird crashes try to access cluster nodes.

### Steps to reproduce

1. Run Seabird
2. Open the cluster
3. Access **Node**
4. Seabird disappear

To get more information, we can run app via CLI
```shell
bash /Applications/Seabird.app/Contents/MacOS/seabird.sh
```
<details>
<summary>output</summary>

```shell
bash /Applications/Seabird.app/Contents/MacOS/seabird.sh
2024/03/03 18:02:35 ERROR gtk_icon_theme_lookup_by_gicon: assertion 'size > 0' failed glib_old_log_api=1 priority=4 glib_domain=Gtk
2024/03/03 18:02:35 ERROR gtk_icon_paintable_is_symbolic: assertion 'GTK_IS_ICON_PAINTABLE (icon)' failed glib_old_log_api=1 priority=4 glib_domain=Gtk
2024/03/03 18:02:35 ERROR gtk_icon_theme_lookup_by_gicon: assertion 'size > 0' failed glib_old_log_api=1 priority=4 glib_domain=Gtk
2024/03/03 18:02:35 ERROR gtk_icon_paintable_is_symbolic: assertion 'GTK_IS_ICON_PAINTABLE (icon)' failed glib_old_log_api=1 priority=4 glib_domain=Gtk
2024/03/03 18:02:35 ERROR gtk_icon_theme_lookup_by_gicon: assertion 'size > 0' failed glib_old_log_api=1 priority=4 glib_domain=Gtk
2024/03/03 18:02:35 ERROR gtk_icon_paintable_is_symbolic: assertion 'GTK_IS_ICON_PAINTABLE (icon)' failed glib_old_log_api=1 priority=4 glib_domain=Gtk
2024/03/03 18:02:35 ERROR gtk_icon_theme_lookup_by_gicon: assertion 'size > 0' failed glib_old_log_api=1 priority=4 glib_domain=Gtk
2024/03/03 18:02:35 ERROR gtk_icon_paintable_is_symbolic: assertion 'GTK_IS_ICON_PAINTABLE (icon)' failed glib_old_log_api=1 priority=4 glib_domain=Gtk
2024/03/03 18:02:35 ERROR gtk_icon_theme_lookup_by_gicon: assertion 'size > 0' failed glib_old_log_api=1 priority=4 glib_domain=Gtk
2024/03/03 18:02:35 ERROR gtk_icon_paintable_is_symbolic: assertion 'GTK_IS_ICON_PAINTABLE (icon)' failed glib_old_log_api=1 priority=4 glib_domain=Gtk
2024/03/03 18:02:35 ERROR gtk_icon_theme_lookup_by_gicon: assertion 'size > 0' failed glib_old_log_api=1 priority=4 glib_domain=Gtk
2024/03/03 18:02:35 ERROR gtk_icon_paintable_is_symbolic: assertion 'GTK_IS_ICON_PAINTABLE (icon)' failed glib_old_log_api=1 priority=4 glib_domain=Gtk
2024/03/03 18:02:35 ERROR gtk_icon_theme_lookup_by_gicon: assertion 'size > 0' failed glib_old_log_api=1 priority=4 glib_domain=Gtk
2024/03/03 18:02:35 ERROR gtk_icon_paintable_is_symbolic: assertion 'GTK_IS_ICON_PAINTABLE (icon)' failed glib_old_log_api=1 priority=4 glib_domain=Gtk
2024/03/03 18:02:35 ERROR gtk_icon_theme_lookup_by_gicon: assertion 'size > 0' failed glib_old_log_api=1 priority=4 glib_domain=Gtk
2024/03/03 18:02:35 ERROR gtk_icon_paintable_is_symbolic: assertion 'GTK_IS_ICON_PAINTABLE (icon)' failed glib_old_log_api=1 priority=4 glib_domain=Gtk
2024/03/03 18:02:35 ERROR gtk_icon_theme_lookup_by_gicon: assertion 'size > 0' failed glib_old_log_api=1 priority=4 glib_domain=Gtk
2024/03/03 18:02:35 ERROR gtk_icon_paintable_is_symbolic: assertion 'GTK_IS_ICON_PAINTABLE (icon)' failed glib_old_log_api=1 priority=4 glib_domain=Gtk
2024/03/03 18:02:45 metrics disabled: no compatible metrics API detected
2024/03/03 18:02:46 ERROR g_object_add_toggle_ref: assertion 'G_IS_OBJECT (object)' failed glib_old_log_api=1 priority=4 glib_domain=GLib-GObject
2024/03/03 18:02:46 ERROR g_object_is_floating: assertion 'G_IS_OBJECT (object)' failed glib_old_log_api=1 priority=4 glib_domain=GLib-GObject
2024/03/03 18:02:46 ERROR g_object_unref: assertion 'G_IS_OBJECT (object)' failed glib_old_log_api=1 priority=4 glib_domain=GLib-GObject
2024/03/03 18:02:46 ERROR g_object_ref: assertion 'G_IS_OBJECT (object)' failed glib_old_log_api=1 priority=4 glib_domain=GLib-GObject
2024/03/03 18:02:46 ERROR gtk_icon_theme_lookup_by_gicon: assertion 'size > 0' failed glib_old_log_api=1 priority=4 glib_domain=Gtk
2024/03/03 18:02:46 ERROR gtk_icon_paintable_is_symbolic: assertion 'GTK_IS_ICON_PAINTABLE (icon)' failed glib_old_log_api=1 priority=4 glib_domain=Gtk
2024/03/03 18:02:46 ERROR gtk_icon_theme_lookup_by_gicon: assertion 'size > 0' failed glib_old_log_api=1 priority=4 glib_domain=Gtk
2024/03/03 18:02:46 ERROR gtk_icon_paintable_is_symbolic: assertion 'GTK_IS_ICON_PAINTABLE (icon)' failed glib_old_log_api=1 priority=4 glib_domain=Gtk
2024/03/03 18:02:46 ERROR gtk_icon_theme_lookup_by_gicon: assertion 'size > 0' failed glib_old_log_api=1 priority=4 glib_domain=Gtk
2024/03/03 18:02:46 ERROR gtk_icon_paintable_is_symbolic: assertion 'GTK_IS_ICON_PAINTABLE (icon)' failed glib_old_log_api=1 priority=4 glib_domain=Gtk
2024/03/03 18:02:46 ERROR gtk_icon_theme_lookup_by_gicon: assertion 'size > 0' failed glib_old_log_api=1 priority=4 glib_domain=Gtk
2024/03/03 18:02:46 ERROR gtk_icon_paintable_is_symbolic: assertion 'GTK_IS_ICON_PAINTABLE (icon)' failed glib_old_log_api=1 priority=4 glib_domain=Gtk
2024/03/03 18:02:46 ERROR gtk_icon_theme_lookup_by_gicon: assertion 'size > 0' failed glib_old_log_api=1 priority=4 glib_domain=Gtk
2024/03/03 18:02:46 ERROR gtk_icon_paintable_is_symbolic: assertion 'GTK_IS_ICON_PAINTABLE (icon)' failed glib_old_log_api=1 priority=4 glib_domain=Gtk
2024/03/03 18:02:46 ERROR gtk_icon_theme_lookup_by_gicon: assertion 'size > 0' failed glib_old_log_api=1 priority=4 glib_domain=Gtk
2024/03/03 18:02:46 ERROR gtk_icon_paintable_is_symbolic: assertion 'GTK_IS_ICON_PAINTABLE (icon)' failed glib_old_log_api=1 priority=4 glib_domain=Gtk
2024/03/03 18:02:46 WARN GtkLabel 0x15166db30 (label) reported min width 9 and natural width 6 in measure() with for_size=9; natural size must be >= min size priority=4 code_file=../gtk/gtksizerequest.c code_line=307 code_func=gtk_widget_query_size_for_orientation glib_domain=Gtk
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: closure error: unexpected panic caught: runtime error: invalid memory address or nil pointer dereference

Closure added at:
	github.com/diamondburned/gotk4/pkg/gtk/v4.(*SignalListItemFactory).ConnectBind at github.com/diamondburned/gotk4/pkg@v0.2.2/gtk/v4/gtk.go:89535
	github.com/getseabird/seabird/internal/ui.(*ListView).createColumns at github.com/getseabird/seabird/internal/ui/list_view.go:142
	github.com/getseabird/seabird/internal/ui.(*ListView).onObjectsChange at github.com/getseabird/seabird/internal/ui/list_view.go:76 [recovered]
	panic: closure error: unexpected panic caught: runtime error: invalid memory address or nil pointer dereference

Closure added at:
	github.com/diamondburned/gotk4/pkg/gtk/v4.(*SignalListItemFactory).ConnectBind at github.com/diamondburned/gotk4/pkg@v0.2.2/gtk/v4/gtk.go:89535
	github.com/getseabird/seabird/internal/ui.(*ListView).createColumns at github.com/getseabird/seabird/internal/ui/list_view.go:142
	github.com/getseabird/seabird/internal/ui.(*ListView).onObjectsChange at github.com/getseabird/seabird/internal/ui/list_view.go:76
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x1049dcb6c]

goroutine 1 [running, locked to thread]:
github.com/diamondburned/gotk4/pkg/core/closure.(*FuncStack).TryRepanic(0x14000a8e420)
	github.com/diamondburned/gotk4/pkg@v0.2.2/core/closure/funcstack.go:118 +0xec
panic({0x105069580?, 0x14000dda310?})
	runtime/panic.go:770 +0x124
github.com/diamondburned/gotk4/pkg/core/closure.(*FuncStack).Panicf(0x14000a8eff0, {0x104b79cec, 0x1b}, {0x14000d191f8, 0x1, 0x1})
	github.com/diamondburned/gotk4/pkg@v0.2.2/core/closure/funcstack.go:104 +0x7e4
github.com/diamondburned/gotk4/pkg/core/closure.(*FuncStack).TryRepanic(0x14000a8eff0)
	github.com/diamondburned/gotk4/pkg@v0.2.2/core/closure/funcstack.go:122 +0xb8
panic({0x1051c9fa0?, 0x107494320?})
	runtime/panic.go:770 +0x124
github.com/getseabird/seabird/api.(*Metrics).Node(...)
	github.com/getseabird/seabird/api/metrics.go:101
github.com/getseabird/seabird/extension.(*Core).CreateColumns.func10(0x14000936398, {0x10567f948?, 0x1400037ac08})
	github.com/getseabird/seabird/extension/core.go:159 +0x4c
github.com/getseabird/seabird/internal/ui.(*ListView).createColumns.func2(0x14000936398)
	github.com/getseabird/seabird/internal/ui/list_view.go:145 +0x84
github.com/diamondburned/gotk4/pkg/gtk/v4._gotk4_gtk4_SignalListItemFactory_ConnectBind(0x14000d196d8?, 0x600001178900, 0x107bb5ae8?)
	github.com/diamondburned/gotk4/pkg@v0.2.2/gtk/v4/gtk_export.go:9423 +0xfc
github.com/diamondburned/gotk4/pkg/gtk/v4._Cfunc_gtk_string_list_append(0x600003b845d0, 0x60000376bfc0)
	_cgo_gotypes.go:45823 +0x30
github.com/diamondburned/gotk4/pkg/gtk/v4.(*StringList).Append.func2(0x600003b845d0, 0x60000376bfc0)
	github.com/diamondburned/gotk4/pkg@v0.2.2/gtk/v4/gtk.go:95157 +0x50
github.com/diamondburned/gotk4/pkg/gtk/v4.(*StringList).Append(0x1400057e3f0, {0x104b86e20, 0x1})
	github.com/diamondburned/gotk4/pkg@v0.2.2/gtk/v4/gtk.go:95157 +0xa0
github.com/getseabird/seabird/internal/ui.(*ListView).onObjectsChange(0x1400067e180, {0x14000232880, 0x6, 0x14000a8e420?})
	github.com/getseabird/seabird/internal/ui/list_view.go:87 +0x3bc
github.com/getseabird/seabird/internal/ui.onChange[...].func1.1()
	github.com/getseabird/seabird/internal/ui/on.go:18 +0x3c
github.com/diamondburned/gotk4/pkg/core/glib._gotk4_sourceFunc(0x103f)
	github.com/diamondburned/gotk4/pkg@v0.2.2/core/glib/glib.go:340 +0xdc
github.com/diamondburned/gotk4/pkg/gio/v2._Cfunc_g_application_run(0x15160e630, 0x1, 0x60000372a6f0)
	_cgo_gotypes.go:13802 +0x34
github.com/diamondburned/gotk4/pkg/gio/v2.(*Application).Run.func3(0x15160e630, 0x1, 0x60000372a6f0)
	github.com/diamondburned/gotk4/pkg@v0.2.2/gio/v2/gio.go:41611 +0x74
github.com/diamondburned/gotk4/pkg/gio/v2.(*Application).Run(0x14000128060, {0x14000192040, 0x1, 0x1})
	github.com/diamondburned/gotk4/pkg@v0.2.2/gio/v2/gio.go:41611 +0x1c4
github.com/getseabird/seabird/internal/ui.(*Application).Run(0x104ee06a0?)
	github.com/getseabird/seabird/internal/ui/application.go:74 +0x3c
main.main()
	github.com/getseabird/seabird/main.go:21 +0xa0
```

<img width="1510" alt="Screenshot 2024-03-03 at 18 10 46" src="https://github.com/getseabird/seabird/assets/88528265/291be304-08ab-4021-814c-ff364a735696">
</details>

### System information
Seabird: v0.2.1
OS: macOS 14.3.1 arm64

<details>
<summary>Additional</summary>

It would be usefully to have "About" information to copy/paste it to the System information section.
<img width="819" alt="Screenshot 2024-03-03 at 18 12 06" src="https://github.com/getseabird/seabird/assets/88528265/f18bcf6f-c0ca-44e4-98d3-04ebfb516643">

</details>

**Comment by jgillich** [comment]
Fixed in 0.2.2 by 2cdbf7ea79a92b43602d5a9d94f4ff3004073ebe
